<h2>Message Queue Settings</h2>
<?php
    $acl = $this->acl;
?>

<?php if ($acl->isAllowed($this->currentUser, 'access newsletter pages')): ?>
<a href="<?php echo $this->url(array(
        'module'    =>'newsletter',
        'controller'=>'index',
        'action'    =>'index'
        ), null, true); ?>">Newsletter</a>
        |
<?php endif; ?>   

<?php if  ($acl->isAllowed($this->currentUser, 'access newsletter pages')): ?>
<a href="<?php echo $this->url(array(
    'module'    =>'newsletter', 
    'controller'=>'settings',
    'action'    =>'index'
    )
  , null, true); ?>">Settings</a>
<?php endif; ?>
     
<?php
    $this->headTitle('Message Queue Settings');
?>
<p>
    We recommend using VERP. BizSense VERP is designed to work with VERP 
    feature of Postfix MTA. VERP enables BizSense to   automatically 
    handle bounce messages. The mail settings below will be used to send 
    emails to the mailing lists. These   settings are separate from site email.
</p>
<?php
    echo $this->message;
?>
<div id="form">
   <?php echo $this->form; ?>
</div>
<div class="div_clear"></div>
