<h2>Close Financial Accounts</h2>
<?php
    $this->headTitle('Close Financial Accounts');
    $acl = $this->acl;
?>

<?php if ($acl->isAllowed($this->currentUser, 'access finance pages')): ?>
<a href="<?php echo $this->url(
    array(
        'module' => 'finance',
        'controller' => 'index',
        'action' => 'index',
    ), 'default', true
);?>">Finance</a> 
<?php endif; ?>

<div id="form">
    <?php  echo $this->form; ?>
</div>
<div class="div_clear"></div>
