<h2>Quote status details</h2>
<?php
    $this->headTitle('Quote status details');
    $this->headScript()->appendFile('/js/BizSense/Crud.js');   
    $quoteStatusDetails = $this->quoteStatus;
?>
<a href="<?php echo $this->url(array(
        'module'        => 'default',
        'controller'    => 'quotestatus',
        'action'        => 'index'
        )); ?>">Quote Status</a>
|

<?php 
    $deleteUrl = $this->url(
                    array(
                        'module' => 'default',
                        'controller' => 'quotestatus',
                        'action' => 'delete',
                    )
                );
                echo $this->deleteButton($deleteUrl); 
 ?>
|

<div class="clearing"> </div>
<table class="data_table">
   <tr>
        <td>Name</td>
        <td><?php echo $this->escape($quoteStatusDetails['name']); ?></td>
   </tr>
   
   <tr>
        <td>Description</td>
        <td><?php echo $this->escape($quoteStatusDetails['description']); ?></td>
   </tr>
</table>

