<h2>Site URL</h2>
<?php
    $this->headTitle('URL');
    echo  $this->message;
    $acl = $this->acl;
?>
<?php if ($acl->isAllowed($this->currentUser, 'administer bizsense')): ?>
<a href="<?php echo $this->url(array(
        'module'        =>  'admin',
        'controller'    =>  'index',
        'action'        =>  'index',
    ), null, true
); ?>">Administer</a>
<?php endif; ?>
<br />

<div id="form">
   <?php echo $this->form; ?>
</div>  
