<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"; 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <title>ACL - Dev Center</title> 
</head> 
<body> 
  <h1 align="center"><?php echo "ACL Info" ?></h1>  
<?php
	echo $this->message;
	echo $this->form;
?>
</body>  
</html> 
