<h2> Lists</h2>
<?php
    $this->headTitle('Lists');
    $this->headScript()->appendFile('/js/BizSense/Crud.js');
    $acl = $this->acl;    
?>

<?php if  ($acl->isAllowed($this->currentUser, 'access newsletter pages')): ?>
<a href="<?php echo $this->url(array(
    'module'    =>'newsletter', 
    'controller'=>'index',
    'action'    =>'index'
    )
  , null, true); ?>">Newsletter</a>
  |
<?php endif; ?>

<?php if  ($acl->isAllowed($this->currentUser, 'access newsletter pages')): ?>
<a href="<?php echo $this->url(array(
    'module'    =>'newsletter', 
    'controller'=>'list',
    'action'    =>'create'
    )
  , null, true); ?>">Create List</a>
<?php endif; ?>

<fieldset class="fieldset_properties">
    <legend>
        <img src="/images/design/search.png"></li>
                     Search
     </legend>
        <?php echo $this->form; ?>
</fieldset>

<?php if (count($this->paginator)): ?>
<table class="data_table">
    <tr>
        <th>Name<?php echo $this->sortButtons("name"); ?></th>
        <th>Description<?php echo $this->sortButtons("description"); ?></th>
        <th>Show in Customer Portal
              <?php echo $this->sortButtons("show_in_customer_portal"); ?></th>
        <th>Automatic bounce handle
             <?php echo $this->sortButtons("auto_bounce_handle"); ?></th>
       <th>Action</th>
    </tr>
<?php foreach ($this->paginator as $item): ?>
<?php $item = $item->toArray(); ?>
    <tr>
        <td><?php echo $this->escape($item['name']); ?></td>
        <td><?php echo $this->escape($item['description']); ?></td>
        <td><?php echo $this->escape(
                $item['show_in_customer_portal']) == 1? 'Yes' : 'No'; ?></td>
        <td><?php echo 
           $this->escape($item['auto_bounce_handle']) == 1? 'Yes': 'No'; ?></td>
        <td><a href="<?php echo $this->url(
                array
                (
                    'module' => 'newsletter',
                    'controller' => 'list',
                    'action' => 'viewdetails',
                    'list_id' => $item['list_id']
                ), 'default', true
            ); ?>">Details</a>

            <a href="<?php echo $this->url(
                array
                (
                    'module' => 'newsletter',
                    'controller' => 'list',
                    'action' => 'edit',
                    'list_id' => $item['list_id']
                ), 'default', true
            ); ?>">Edit</a>
            <?php 
                $deleteUrl = $this->url(
                    array(
                        'module' => 'newsletter',
                        'controller' => 'list',
                        'action' => 'delete',
                        'list_id' =>$this->escape($item['list_id'])
                    )
                );
                echo $this->deleteButton($deleteUrl); 
             ?>
         </td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif; ?>

<?php
    if ($this->wasSearched and !count($this->paginator)) {
        echo "<br />There are no records matching the search criteria";
    }
?>

<div class="pagination">
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'search.phtml'); ?>
</div>
<div class="div_clear"></div>

