<h2>Create Cash Deposit</h2>
<?php
    $this->dojoLayer('common');
    $this->headTitle('Cash Deposit');
    $acl = $this->acl;    
?>

<?php if ($acl->isAllowed($this->currentUser, 'access finance pages')): ?>
<a href="<?php echo $this->url(
    array(
        'module' => 'finance',
        'controller' => 'bankaccount',
        'action' => 'index',
    ), 'default', true
);?>">Bank Account</a> |
<?php endif; ?>

<div id="form">
    <?php  echo $this->form; ?>
</div>
<div class="div_clear"></div>
