<html>
<head>
<title>BizSense Installer</title>
<style type="text/css" media="all">@import <?php echo $this->baseUrl(); ?>"/css/bizsense.css";</style>
</head>
<body>
<div id="container">
    
        <div id="header">
        
            <div id="logo">
               
            </div>
     
            <div id="greet">
                
            </div>
            
            <div id="header_text">
                Binary Vibes BizSense Installer!
            </div>
        </div>
        
        <div id="menu">
		    
		</div><!-- end of menu -->
		
		<div id="content">
		    <div id="form">
		    <?php
	              echo $this->message;
	              echo $this->form;
	                
                  if (isset($this->messages)) {
                    foreach ($this->messages as $message) {
                        echo $message . "<br />";
                    }
                  }

                  if (isset($this->installed) and $this->installed === true){
                    echo "<br />The application has been successfully installed.";
                    echo "<br />You may now <a href=\"/user/login\">login</a> as administrator";
                  }
	        ?>
	        </div>
	        <div class="div_clear"> </div>
		</div><!-- end of content -->
</div>



</body>  
</html> 
