<h2>Calls</h2>

<?php
    $this->headTitle('Calls');
    $this->dojoLayer('common');
    $acl = $this->acl;    
?>

<?php if  ($acl->isAllowed($this->currentUser, 'create calls')): ?>
<a href="<?php echo $this->url(array(
        'module'        => 'activity',
        'controller'    => 'call',
        'action'        => 'create'
        )); ?>">Schedule Call</a>
&nbsp;|&nbsp;
<?php endif; ?>

<?php if  ($acl->isAllowed($this->currentUser, 'access call pages')): ?>
<a href="<?php echo $this->url(array(
        'module'        => 'activity',
        'controller'    => 'callstatus',
        'action'        => 'index'
        )); ?>">Call Status</a>
<?php endif; ?>


<div id="form">
<?php echo $this->form; ?>
</div>
<div class="div_clear"></div>


<?php $paginator = ( $this->paginator); ?>

<?php if (count($this->paginator)): ?>
    <table class="data_table">
        <tr>
            <th class="short">Title<?php echo $this->sortButtons("name"); ?></th>
            <th class="medium_short">Start date<?php echo $this->sortButtons("start_date"); ?></th>
            <th class="medium_short">Status</th>
            <th class="short">Action</th>
        </tr>
    
<?php foreach ($paginator as $item) {
    $itemRow = $item->toArray();
    $call_id = $this->escape($itemRow['call_id']);
?>
    <tr>
        <td>
            <?php echo $this->escape($itemRow['name']); ?>
        </td>
        <td>
            <?php echo $this->escape($this->timestampToHuman($itemRow['start_date'])); ?>
        </td>
        <td>
            <?php 
                $callStatusModel = new Core_Model_Activity_Call_Status();
                $callStatusModel->setCallStatusId($itemRow['call_status_id']);
                $statusRecord = $callStatusModel->fetch();
                echo $this->escape($statusRecord['name']); 
            ?>
        </td>
        <td>
        <?php if  ($acl->isAllowed($this->currentUser, 'view all calls')): ?>
           <a href="<?php 
                echo $this->url(array(
                    'module'        =>  'activity', 
                    'controller'    =>  'call', 
                    'action'        =>  'viewdetails', 
                    'call_id'    =>  $call_id,
                ));                    
            ?>"><span>View</span>
            </a>
          <?php endif; ?>
                &nbsp;
          <?php if  ($acl->isAllowed($this->currentUser, 'edit all calls')): ?>
            <a href="<?php 
                echo $this->url(array(
                    'module'        =>  'activity', 
                    'controller'    =>  'call', 
                    'action'        =>  'edit', 
                    'call_id'    =>  $call_id,
                    )); 
             ?>"><span>Edit</span>
                </a>
            <?php endif; ?>
            </td>
    </tr>
<?php
    }
?>
    </table>
<?php endif; ?>

<?php
        if ($this->wasSearched and !count($this->paginator)) {
            echo "<br />There are no records matching the search criteria";
        }
?>

<div class="pagination">
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'search.phtml'); ?>
</div>
<div class="div_clear"></div>
