<h2>Call Notes</h2>  
<?php 
    $this->headTitle('Call Notes');
    $call_id = $this->escape($this->callId);
    $acl = $this->acl;    
?>

<?php if  ($acl->isAllowed($this->currentUser, 'access call pages')): ?>
<a href="<?php echo $this->url(array(
        'module'        =>  'activity',
        'controller'    =>  'call',
        'action'        =>  'viewdetails',
        'call_id'    =>  $call_id,
    ));?>">Call</a>
|
<?php endif; ?>

<?php if  ($acl->isAllowed($this->currentUser, 'access call pages')): ?>
<a href="<?php echo $this->url(array(
        'module'        =>  'activity',
        'controller'    =>  'call',
        'action'        =>  'createnotes',
        'call_id'    =>  $call_id,
    ));?>">Create note</a>
<?php endif; ?>

<div class="clearing">
&nbsp;
</div>
<?php
if (count($this->paginator)): ?>
<p>
Total number of notes : <?php echo $this->paginator->getAdapter()->count(); ?>
</p>

<table class="data_table">
<tr>
<th class="short">Notes</th>
<th class="mediumshort">Created</th>
</tr>
<?php foreach ($this->paginator as $item): ?>
<?php
    $itemsArray = $item->toArray();
?>
<tr>
    <?php 
        echo "<td>";
        echo $this->escape($itemsArray['notes']);
        echo "</td>";

        echo "<td>";
        echo $this->escape($this->timestampToHuman($itemsArray['created']));
        echo "</td>";

    ?>
</tr>

<?php endforeach; ?>
<?php endif; ?>

</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'search.phtml'); ?>
