<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Error</title>
</head>
<body>
    <h1>404 Page Not Found</h1>

  <p> 
	My friend, your lucky number for the day is 404.
		
  </p>
  <p>
	The administrator has been notified of this error. Please contact BizSense administrator for any questions.
  </p>

<?php
$request = Zend_Controller_Front::getInstance()->getRequest();
$message = 'access voilation';
$message .= "\n IP Address \n" . Zend_Json::encode($request->getServer('REMOTE_ADDR')) . "\n";
$message .= "\n HTTP AGENT \n" . Zend_Json::encode($request->getServer('HTTP_USER_AGENT')) . "\n";
$message .= "\n Request params\n" .Zend_Json::encode($request->getParams());
$this->fileLogger($message);
?>

</body>
</html>
