<h1>Delete Opportunity</h1>
<?php
    $this->headTitle('Delete Opportunity');
    $opportunity = $this->opportunity;
?>
  <table class="data_table">
        <tr><td>Name </td><td> <?php  echo $this->escape($opportunity->name); ?></td></tr>
        <tr><td>Description </td><td> <?php  echo $this->escape($opportunity->description); ?></td></tr>
        <tr><td>Amount </td><td> <?php  echo $this->escape($opportunity->amount); ?></td></tr>
    </table>
<?php
    echo $this->message;
   
    echo "<br /> Are you sure you want to delete this opportunity? The action cannot be undone."; 
    echo $this->form;
?>
  
