<h2>Editing Opportunity</h2>
<?php
    $this->dojoLayer('common');
    $this->headTitle('Edit Opportunity Details');
	echo $this->message;
?>
<div id="form">
   <?php echo $this->form; ?>
</div>
<div class="div_clear"></div>
<?php

	if (isset($this->message)) {
		echo "<br /><a href=\"" . $this->url(array(
		        'module' => 'default', 
		        'controller' => 'opportunity', 
		        'action' => 'viewdetails', 
		        'id' => $this->opportunityId)) . "\">
		        View details</a>";
		echo " | <a href=\"" . $this->url(array(
		        'module' => 'default', 
		        'controller' => 'opportunity'), NULL, true) . "\">
		        Opportunities Home</a>";
	}
	
