<h2>Opportunity Notes</h2>  
<?php 
    $this->headTitle('Opportunity Notes');
    $acl = $this->acl;
    $opportunity_id = $this->escape($this->opportunityId);
?>

<?php if  ($acl->isAllowed($this->currentUser, 'access opportunity pages')): ?>
<a href="<?php echo $this->url(array(
        'module'        =>  'default',
        'controller'    =>  'opportunity',
        'action'        =>  'viewdetails',
        'opportunity_id'    =>  $opportunity_id,
    ));?>">Opportunity</a>
|
<?php endif; ?>

<?php if  ($acl->isAllowed($this->currentUser, 'access opportunity pages')): ?>
<a href="<?php echo $this->url(array(
        'module'        =>  'default',
        'controller'    =>  'opportunity',
        'action'        =>  'createnote',
        'opportunity_id'    =>  $opportunity_id,
    ));?>">Create note</a>
|
<?php endif; ?>

<div class="clearing">
&nbsp;
</div>
<?php

if (count($this->paginator)): ?>
<p>
Total number of notes : <?php echo $this->paginator->getAdapter()->count(); ?>
</p>

<table class="data_table">
<tr>
<th>Notes</th>
<th>Created</th>
<th>Created By</th>
</tr>
<?php foreach ($this->paginator as $item): ?>
<?php
    $itemsArray = $item->toArray();
?>
<tr>
    <?php 
        echo "<td>";
        $notes = $this->escape($itemsArray['notes']);
        echo nl2br($notes);
        echo "</td>";

        echo "<td>";
        echo $this->timestampToHuman($this->escape($itemsArray['created']));
        echo "</td>";
        
        echo "<td>";
        echo $this->userHyperlink($this->escape($itemsArray['created_by']));
        echo "</td>";

    ?>
</tr>

<?php endforeach; ?>
<?php endif; ?>

</table>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'search.phtml'); ?>
