<h2>Lead source details</h2>
<?php
    $this->headTitle('View lead source details');
    $this->headScript()->appendFile('/js/BizSense/Crud.js');   
    $leadSourceDetails = $this->leadSource;
?>
<a href="<?php echo $this->url(array(
        'module'        => 'default',
        'controller'    => 'leadsource',
        'action'        => 'index'
        )); ?>">Lead Source</a>
&nbsp;|&nbsp;
<?php
     $deleteUrl = $this->url(
                    array(
                        'module' => 'default',
                        'controller' => 'leadsource',
                        'action' => 'delete'
                    )
                );
                echo $this->deleteButton($deleteUrl); 
?>

<div class="clearing"> </div>
<table class="data_table">
   <tr>
        <td>Name</td>
        <td><?php echo $this->escape($leadSourceDetails['name']); ?></td>
   </tr>
   <tr>
        <td>Description</td>
        <td><?php echo $this->escape($leadSourceDetails['description']); ?></td>
   </tr>
</table>

