<h2>Lead status details</h2>
<?php
    $this->headTitle('View lead details');
    $this->headScript()->appendFile('/js/BizSense/Crud.js');
    $leadStatusDetails = $this->leadStatus;
?>
<a href="<?php echo $this->url(array(
        'module'        => 'default',
        'controller'    => 'leadstatus',
        'action'        => 'index'
        )); ?>">Lead Status</a>
&nbsp;|&nbsp;

<?php
     $deleteUrl = $this->url(
                    array(
                        'module' => 'default',
                        'controller' => 'leadstatus',
                        'action' => 'delete'
                    )
                );
                echo $this->deleteButton($deleteUrl); 
?>

<div class="clearing"> </div>
<table class="data_table">
   <tr>
        <td>Name</td>
        <td><?php echo $this->escape($leadStatusDetails['name']); ?></td>
   </tr>
   <tr>
        <td>Description</td>
        <td><?php echo $this->escape($leadStatusDetails['description']); ?></td>
   </tr>
</table>

