<h2>Edit task status</h2>
<?php
    $this->dojoLayer('common');
    $this->headTitle('Edit task status details');
    $acl = $this->acl;
?>
<?php if  ($acl->isAllowed($this->currentUser, 'access task pages')): ?>
    <a href="<?php echo $this->url(array(
        'module'        => 'activity',
        'controller'    => 'taskstatus',
        'action'        => 'index'
        )); ?>">Task Status</a>
<?php endif; ?>        

<div id="form">
   <?php echo $this->form; ?>
</div>
<div class="div_clear"></div>
