<h2>Task status details</h2>
<?php
    $this->headTitle('View task details');
    $this->headScript()->appendFile('/js/BizSense/Crud.js'); 
    $taskStatusDetails = $this->taskStatus;
    $acl = $this->acl;
?>

<?php if  ($acl->isAllowed($this->currentUser, 'access task pages')): ?>
<a href="<?php echo $this->url(array(
        'module'        => 'activity',
        'controller'    => 'task',
        'action'        => 'index'
        )); ?>">Tasks</a>
&nbsp;|&nbsp;
<?php endif; ?>

<?php if  ($acl->isAllowed($this->currentUser, 'access task pages')): ?>
<a href="<?php echo $this->url(array(
        'module'        => 'activity',
        'controller'    => 'taskstatus',
        'action'        => 'index'
        )); ?>">Task Status</a> |
<?php endif; ?>

<?php if  ($acl->isAllowed($this->currentUser, 'access task pages')): 
    $deleteUrl = $this->url(
                    array(
                        'module' => 'activity',
                        'controller' => 'taskstatus',
                        'action' => 'delete',
                    )
                );
                echo $this->deleteButton($deleteUrl); 
 endif; ?>
|
<div class="clearing"> </div>
<table class="data_table">
   <tr><td>Name</td><td><?php echo $this->escape($taskStatusDetails['name']); ?></td></tr>
   <tr><td>Description</td><td><?php echo $this->escape($taskStatusDetails['description']); ?></td></tr>
</table>

