<h2>Meetings</h2>

<?php
    $this->headTitle('Meetings');
    $this->dojoLayer('common');
    $acl = $this->acl;    
?>
<div class="clearing">
</div>

<?php if  ($acl->isAllowed($this->currentUser, 'create meetings')): ?>
<a href="<?php echo $this->url(array(
        'module'        => 'activity',
        'controller'    => 'meeting',
        'action'        => 'create'
        )); ?>">Schedule Meeting</a>
&nbsp;|&nbsp;
<?php endif; ?>

<?php if  ($acl->isAllowed($this->currentUser, 'access meeting pages')): ?>
<a href="<?php echo $this->url(array(
        'module'        => 'activity',
        'controller'    => 'meetingstatus',
        'action'        => 'index'
        )); ?>">Meeting Status</a>
<?php endif; ?>


<div id="form">
<?php echo $this->form; ?>
</div>
<div class="div_clear"></div>
<?php $paginator = ( $this->paginator); ?>

<?php if (count($this->paginator)): ?>
    <table class="data_table">
        <tr>
            <th class="short">Title
                            <?php echo $this->sortButtons("name"); ?></th>
            <th class="medium_short">Start date
                           <?php echo $this->sortButtons("start_date"); ?></th>
            <th class="medium_short">Status</th>
            <th class="short">Action</th>
        </tr>
    
<?php foreach ($paginator as $item) {
    $itemRow = $item->toArray();
    $meeting_id = $this->escape($itemRow['meeting_id']);
?>
    <tr>
        <td>
            <?php echo $this->escape($itemRow['name']); ?>
        </td>
        <td>
            <?php echo $this->escape(
                           $this->timestampToHuman($itemRow['start_date'])); ?>
        </td>
        <td>
            <?php 
                $meetingStatusModel = new Core_Model_Activity_Meeting_Status();
                $meetingStatusModel->setMeetingStatusId($itemRow['meeting_status_id']);
                $statusRecord = $meetingStatusModel->fetch();
                echo $this->escape($statusRecord['name']); 
            ?>
        </td>
        <td>
            <?php if  ($acl->isAllowed($this->currentUser, 'view all meetings')): ?>
           <a href="<?php 
                echo $this->url(array(
                    'module'        =>  'activity', 
                    'controller'    =>  'meeting', 
                    'action'        =>  'viewdetails', 
                    'meeting_id'    =>  $meeting_id,
                ));                    
            ?>"><span>View</span>
            </a>
            <?php endif; ?>
                &nbsp;
            <?php if  ($acl->isAllowed($this->currentUser, 'edit all meetings')): ?>
            <a href="<?php 
                echo $this->url(array(
                    'module'        =>  'activity', 
                    'controller'    =>  'meeting', 
                    'action'        =>  'edit', 
                    'meeting_id'    =>  $meeting_id,
                    )); 
             ?>"><span>Edit</span>
                </a>
            <?php endif; ?>
            </td>
    </tr>
<?php
    }
?>
    </table>
<?php endif; ?>
<?php
        if ($this->wasSearched and !count($this->paginator)) {
            echo "<br />There are no records matching the search criteria";
        }
?>

<div class="pagination">
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'search.phtml'); ?>
</div>
<div class="div_clear"></div>

