<?php
    $this->dojoLayer('common');
    $this->headTitle('Create Sales Return');
?>
<?php
    $form = $this->form;
?>
<h2>Create Sales Return</h2>

<?php 
    $this->headScript()->appendFile('/js/BizSense/Invoice/ReturnItems.js'); 
?>

<?php
        $returnedItemsJavaScript = '';
        $returnedItemsJavaScript .= 'var returnedItems = ' . 
                                                $this->returnedItemsJSON . '; ';
        $returnedItemsJavaScript .= ' var toRecreate = true;';

        $this->headScript()->appendScript($returnedItemsJavaScript);
        $this->headScript()->appendFile('/js/BizSense/Invoice/RecreateItems.js');
?>

<p class="error_messages">
<?php
if (isset($this->itemMessages)) {
    echo "The following erros occured while submitting the invoice items. 
        Please correct them and submit the form again. <br /><br />";
    foreach ($this->itemMessages as $message) {
        echo $message . "<br />";
    }        
}
?>
</p>
<form method="post" action="<?php echo $form->getAction(); ?>">
<table id="items_table" class="data_table">
    <tr>
        <th>Item</th>
        <th>Description</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Tax type</th>
        <th>Amount</th>
        <th>Action</th>
    </tr>
    <tr>
    
    </tr>
</table>

<fieldset class="fieldset_medium">
<legend>
Meta data
</legend>
<div id="form">
<?php
$form = $this->form;
$elements = $form->getElements();
foreach ($elements as $element) {
    echo $element;
}
?>
</div>
</form>
</fieldset>
</form>
