<h2>Create note</h2>
<?php
    $this->headTitle('Create lead note');
    $acl = $this->acl;
?>
<?php if ($acl->isAllowed($this->currentUser, 'access contact pages')): ?>
<a href="<?php echo $this->url(
    array(
        'module' => 'default', 
        'controller' => 'contact', 
        'action' => 'viewdetails',
        'contact_id' => $this->escape($this->contactId)
    )
);?>">View contact details</a> 
<?php endif; ?>
            
<div id="form">
   <?php echo $this->form; ?>
</div>
<div class="div_clear"></div>
