INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, 'AADI', 200, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, 'AAFJE', 300, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' AAID', 400, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' AALIYAH', 500, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' AARALYN', 600, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' AARON', 700, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABA', 800, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABABUO', 900, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABANA', 1000, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABARNE', 1100, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABAY', 1200, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABBA', 1300, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABBATHA', 1400, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABBEY', 1500, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABBIE', 1600, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABBOTT', 1700, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABBY', 1800, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABCDE', 1900, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABDIEL', 2000, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABDUKRAHMAN', 2100, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABDULKAREEM', 2200, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABDULLAH', 2300, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABDULRAHMAN', 2400, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABE', 2500, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABEDNEGO', 2600, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABEEKU', 2700, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABEJE', 2800, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABEL', 2900, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABELARD', 3000, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABENI', 3100, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABHAY', 3200, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABIA', 3300, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABIBA', 3400, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABIE', 3500, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABIGAIL', 3600, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABILENE', 3700, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABIYRAM', 3800, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABNER', 3900, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRA', 4000, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRAHAM', 4100, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRAM', 4200, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRIANNA', 4300, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRIELLE', 4400, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRIENDA', 4500, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRIL', 4600, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, 'AADI', 4700, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, 'AAFJE', 4800, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' AAID', 4900, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' AALIYAH', 5000, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' AARALYN', 5100, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' AARON', 5200, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABA', 5300, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABABUO', 5400, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABANA', 5500, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABARNE', 5600, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABAY', 5700, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABBA', 5800, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABBATHA', 5900, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABBEY', 6000, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABBIE', 6100, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABBOTT', 6200, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABBY', 6300, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABCDE', 6400, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABDIEL', 6500, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABDUKRAHMAN', 6600, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABDULKAREEM', 6700, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABDULLAH', 6800, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABDULRAHMAN', 6900, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABE', 7000, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABEDNEGO', 7100, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABEEKU', 7200, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABEJE', 7300, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABEL', 7400, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABELARD', 7500, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABENI', 7600, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABHAY', 7700, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABIA', 7800, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABIBA', 7900, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABIE', 8000, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABIGAIL', 8100, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABILENE', 8200, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABIYRAM', 8300, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABNER', 8400, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRA', 8500, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRAHAM', 8600, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRAM', 8700, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRIANNA', 8800, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRIELLE', 8900, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRIENDA', 9000, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABRIL', 9100, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, 'AADI', 9200, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, 'AAFJE', 9300, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' AAID', 9400, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' AALIYAH', 9500, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' AARALYN', 9600, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' AARON', 9700, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABA', 9800, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABABUO', 9900, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABANA', 10000, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABARNE', 10100, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;

INSERT INTO `opportunity` ( `customer_type`, `name`, `amount`, `expected_close_date`, `description`, `lead_source_id`, `sales_stage_id`, `account_id`, `contact_id`, `assigned_to`, `branch_id`, `created`, `created_by`, `updated`, `campaign_id`) VALUES ( 1, ' ABAY', 10200, 1278527400, 'Lorem ipsuLorem ipsum dolor sit aLorem ipsum dolor sit amet, consectetur adipiscing elit.met, consectetur adipiscing elit.m dolor sit amet, consectetur adipiscing elit.', 14, 1, 1, 0, 1, 1, 1278496025, 1, 1279704802, NULL) ;


