<h2>Tax Cash Payment Details</h2>

<?php
    $this->headTitle('Tax Cash Payment Details');
    $acl = $this->acl;
?>

<?php
	$payment = $this->payment;
	$paymentId = $this->paymentId;
?>

<p>
<a href="<?php echo $this->url(
    array(
        'module' => 'finance',
        'controller' => 'payment',
        'action' => 'index',
    ), 'default', true
);?>">Payment</a>
 |

<a href="<?php echo $this->url(
    array(
        'module' => 'finance',
        'controller' => 'payment',
        'action' => 'edittaxcash',
        'payment_id' => $paymentId
    ), 'default', true
);?>">Edit</a>

|

<a href="<?php echo $this->url(
    array(
        'module' => 'finance',
        'controller' => 'payment',
        'action' => 'delete',
        'payment_id' => $paymentId
    ), 'default', true
);?>">Delete</a>
</p>

<table class="data_table">
    <tr>
        <td>Amount</td>
        <td class="mediumshort">
            <?php echo $payment['amount']; ?>
        </td>
    </tr>
	<tr>
        <td>Payment Date</td>
        <td>
            <?php echo $this->timestampToHuman($payment['date']); ?>
        </td>
    </tr>
    <tr>
        <td>Created on</td>
        <td><?php echo $this->timestampToHuman($payment['created']); ?></td>
    </tr>
    <tr>
        <td>Created by</td>
        <td><?php echo $this->userHyperlink($payment['created_by']); ?></td>
    </tr>
    <tr>
        <td>Party type</td>
        <td>
            <?php 
                echo "Payment to tax";
            ?>
        </td>
    </tr>
    
</table>
    
