<h2>Edit meeting status</h2>
<?php
    $this->dojoLayer('common');
    $this->headTitle('Edit meeting status details');
    $acl = $this->acl;    
?>
<?php if ($acl->isAllowed($this->currentUser, 'access meeting pages')): ?>
<a href="<?php echo $this->url(array(
        'module'        => 'activity',
        'controller'    => 'meetingstatus',
        'action'        => 'index'
        )); ?>">Meeting Status</a>
<?php endif; ?>

<div id="form">
   <?php echo $this->form; ?>
</div>
<div class="div_clear"></div>

