<h2>Edit call status</h2>
<?php
    $this->dojoLayer('common');
    $this->headTitle('Edit call status details');
    $acl = $this->acl;    
?>
<?php if  ($acl->isAllowed($this->currentUser, 'create leads')): ?>
    <a href="<?php echo $this->url(array(
        'module'        => 'activity',
        'controller'    => 'callstatus',
        'action'        => 'index'
        )); ?>">Call Status</a>
<?php endif; ?>        
        
<div id="form">
   <?php echo $this->form; ?>
</div>
<div class="div_clear"></div>
