<h2>Call status details</h2>
<?php
    $this->headTitle('View call details');
    $this->headScript()->appendFile('/js/BizSense/Crud.js');  
    $callStatusDetails = $this->callStatus;
    $acl = $this->acl;    
?>
<?php if  ($acl->isAllowed($this->currentUser, 'access call pages')): ?>
<a href="<?php echo $this->url(array(
        'module'        => 'activity',
        'controller'    => 'callstatus',
        'action'        => 'index'
        )); ?>">Call Status</a> |
<?php endif; ?>

<?php if  ($acl->isAllowed($this->currentUser, 'access call pages')):
    $deleteUrl = $this->url(
                    array(
                        'module' => 'activity',
                        'controller' => 'callstatus',
                        'action' => 'delete'
                    )
                );
                echo $this->deleteButton($deleteUrl); 
 endif; ?>
|

<table class="data_table">
   <tr>
        <td>Name</td>
        <td><?php echo $this->escape($callStatusDetails['name']); ?></td>
   </tr>
   
   <tr>
        <td>Description</td>
        <td><?php echo $this->escape($callStatusDetails['description']); ?></td>
   </tr>
</table>

