<h2>Create note</h2>
<?php
    $this->headTitle('Create lead note');
    $acl = $this->acl;
?>
<?php if  ($acl->isAllowed($this->currentUser, 'access lead pages')): ?>
<a href="<?php echo $this->url(array(
            'module'        =>  'default', 
            'controller'    =>  'lead', 
            'action'        =>  'viewdetails', 
            'lead_id'    => $this->escape($this->leadId)
        ), NULL, TRUE) ; ?>">View lead details</a> 
<?php endif; ?>
<div id="form">
   <?php echo $this->form; ?>
</div>
